services:
  - type: web
    name: dinesh-tweet-generator
    runtime: python
    buildCommand: pip install --upgrade pip && pipenv install --deploy
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PINECONE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false